name: Flutter Clean Architecture CI/CD with Github Action

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint_test:
    name: Clean & Run UT
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          channel: master
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: general
          SLACK_COLOR: ${{ job.status }} # or a specific color like 'good' or '#ff00ff'
          SLACK_ICON: https://github.com/rtCamp.png?size=48
          SLACK_MESSAGE: 'Post Content :rocket:'
          SLACK_TITLE: Post Title
          SLACK_USERNAME: rtCamp
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

      - name: Flutter clean cache
        run: flutter clean

      - name: Get dependences
        id: packages-get
        run: flutter pub get

      - name: Check lint
        id: code-convention
        run: flutter analyze

      - name: Run UT
        id: run-unit-test
        run: flutter test --coverage lib/

      - name: Generate coverage report
        uses: zgosalvez/github-actions-report-lcov@v1
        with:
          coverage-files: coverage/lcov.info
          minimum-coverage: 10
          artifact-name: code-coverage-report
          github-token: ${{ secrets.GITHUB_TOKEN }}
          working-directory: ./

#  build_ios:
#    name: Build Flutter (iOS)
#    needs: lint_test
#    runs-on: macos-latest
#    steps:
#      - uses: actions/checkout@v2
#      - uses: actions/setup-java@v1
#        with:
#          java-version: '12.x'
#      - uses: subosito/flutter-action@v1
#        with:
#          channel: master
#
#      - name: Build ios
#        run: flutter build ios --debug --flavor dev --no-codesign
#
#  build_apk:
#    name: Build Flutter (Android)
#    runs-on: ubuntu-latest
#    needs: lint_test
#    steps:
#      - uses: actions/checkout@v2
#      - uses: actions/setup-java@v1
#        with:
#          java-version: '12.x'
#      - uses: subosito/flutter-action@v1
#        with:
#          channel: master
#
#      - name: Build android
#        run: flutter build apk --debug --flavor dev --dart-define=FLAVOR=dev
#
#  build_exe:
#    name: Build for Windows
#    runs-on: windows-latest
#    needs: lint_test
#    steps:
#      - uses: actions/checkout@v2
#      - uses: subosito/flutter-action@v1
#        with:
#          channel: master
#      - name: Enable desktop support for Flutter
#        run: flutter config --enable-windows-desktop
#
#      - name: Build Windows Debug
#        run: |
#          flutter packages get
#          flutter build -v windows --debug